### ISSUE TITLE
Can't find on chrome web store

### ISSUE THREAD

**Issue by rEnr3n** [NetSepio/ChromiumExtension#1]
I searched for netsepio on the chrome web store and I got no results. Is it up?

**Comment by Shachindra** [comment]
![image](https://user-images.githubusercontent.com/5115199/170012747-d84d256f-1cf2-4849-87b8-f385a427e3c7.png)

We've submitted the extension for review in the Chrome Web Store. We'll make an announcement once the listing is complete.

**Comment by Shachindra** [comment]
The Web Store listing is now complete.

Link: https://chrome.google.com/webstore/detail/netsepio/bbkfclgnbddljhepbfpongcollhocghd

![image](https://user-images.githubusercontent.com/5115199/170087092-df373ed3-94fc-438f-91b4-edea9a2cf11a.png)
