### ISSUE TITLE
WebApp Not running 

### ISSUE THREAD

**Issue by aryasoni2608** [NetSepio/ChromiumExtension#2]
There is a problem occuring in running the Chromium Extension WebApp? Can you help me with building it @vickyshaw29 ?

**Comment by vickyshaw29** [comment]
You might be following the wrong steps . I will write the steps below just follow it and you are good to go :)
For local : 
The process is --> "npm run build" a dist folder will be created  -> go to chrome developer tools and upload that dist folder and it will start .
And regarding your concern that is to run the extension as a web app you need to copy the id of your uploaded dist and then run it like this "chrome-extension://your_uploaded_folderId/popup.html " and It will start as a web app 
Apart from all these you can also install  the extension from the chrome web store  its already there .Let me know if you still face any issue . Thanks
